### PR TITLE
Enhance the tutorial on how to set up a project.

### PR DESCRIPTION
**Pull request by tobiasraabe**
#### Changes

Follow-up to https://github.com/pytask-dev/cookiecutter-pytask-project/pull/8#discussion_r802531424

- Remove `conda develop`.
- Replace setup.py by setup.cfg and pyproject.toml.

### CODE REVIEW

**Comment by tobiasraabe** [comment]
@hmgaudecker, I mention only the old setup.py approach since I documenting setuptools-scm feels like taking a big detour. What do you think? Is it fine?

https://pytask-dev.readthedocs.io/en/latest/tutorials/how_to_set_up_a_project.html?highlight=setup.py#setup-py

**Comment by hmgaudecker** [comment]
TBH, it sounds a bit like this will end up in documentation hell, leaving users confused.

IIUC, the same should be possible replacing `setup.py` with `pyproject.toml`. Then referring to `setuptools_scm` would be just a matter of changing the entries of that file?

**Comment by hmgaudecker** [comment]
What do you mean by "the same behavior"? Finding the stuff in `src` ? Or using the git tags etc.? I thought the latter was what `setuptools-scm` does, that you could leave out. No idea about the `setup.py`.

**Comment by tobiasraabe** [comment]
With the same behavior I mean: finding stuff in src, adding metadata to the package, setting a version (dynamically via setuptools-scm or static via the `version` keyword in setup.py).

This can be done all in setup.py. Simple but inconsistent.

Or you need to do the four points from the post above. Consistent, but more documentation.

pyproject toml is used by setuptools-scm to store information on how to build the package.

**Comment by hmgaudecker** [comment]
Great, thanks! I still don't quite understand why all four steps are needed. A little research, maybe too shallow... 

- I could set the version directly in `setup.cfg`, [it seems](https://setuptools.pypa.io/en/latest/userguide/quickstart.html) -- why `setuptools-scm` except for the extra comfort?
- [Looks like with recent-enough pip](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#development-mode), `setup.py` can go?  Are you fine with requiring that?

In case I am not mistaken, it would just be `pyproject.toml` + `setup.cfg` instead of `setup.py`?

**Comment by tobiasraabe** [comment]
- Exactly for the extra comfort :). Releasing a new version just becomes writing a new release on Github with a tag.

- This pip version is from last April. I guess I am fine with that. I dont know why someone runs on an older version.

**Comment by hmgaudecker** [comment]
> Exactly for the extra comfort :). Releasing a new version just becomes writing a new release on Github with a tag.

Yeah, that's why I would keep that in the templates, but I agree with you ^^^^^ that documenting it here would be a bit of a detour. 

> This pip version is from last April. I guess I am fine with that. I dont know why someone runs on an older version.

Cool. So `pyproject.toml` + `setup.cfg`  it is, ditching `setup.py`.

While you are at it: I would change

> every time you recreate your Python environment

to 

> should you recreate your Python environment

Most people will not do that very often.

**Comment by tobiasraabe** [comment]
Hi @hmgaudecker, it is done. If you'd like, you can have a final look and then we merge it. Thanks for the discussion!

**Comment by hmgaudecker** [comment]
Great, thank you!

**Pull request merged**
