### PR TITLE
Fix typo in link and adjust documentation for warnings.

### PR DESCRIPTION
**Pull request by hmgaudecker**
Triviality that I noted while actually trying to follow that link in an application.

### CODE REVIEW

**Comment by hmgaudecker** [comment]
While actually looking at [that page](https://pytask-dev.readthedocs.io/en/stable/how_to_guides/capture_warnings.html#controlling-warnings): Is the exact syntax described somewhere? After parsing the examples, my best guess before actually trying is

`action:regex:warningtype`

but it would be nice to have that written out explicitly.

Aside: Explanation of the order in which they are processed would be good. From the described behaviour, I suppose that latter items take precedence over former items in the list?

**Comment by hmgaudecker** [comment]
I re-ordered the section a little bit. At least for an old person like me, parsing the example was very hard because the respective order of the text and the code did not line up. Hope it works like this.

**Comment by tobiasraabe** [comment]
Thanks! It is better now.

**Comment by hmgaudecker** [comment]
Cool. LMK if there is anything else you want me to do before merging this!

**Review by tobiasraabe — APPROVED** [review]
No, all good. Thank you very much!

**Pull request merged**
